webtalk_init -webtalk_dir C:/Users/Ray/Desktop/Arquitectura/Archivo_de_registros/registro/registro.sim/sim_1/behav/xsim/xsim.dir/tb_registro_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 26 11:33:30 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5fddceac-b2c2-4060-8bb1-b135ca9533da" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5ce846e7b76d44a580f23e7e9b47fdc5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX-8800P Radeon R7, 12 Compute Cores 4C+8G " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5820_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3774668204 -regid "" -xml C:/Users/Ray/Desktop/Arquitectura/Archivo_de_registros/registro/registro.sim/sim_1/behav/xsim/xsim.dir/tb_registro_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Ray/Desktop/Arquitectura/Archivo_de_registros/registro/registro.sim/sim_1/behav/xsim/xsim.dir/tb_registro_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Ray/Desktop/Arquitectura/Archivo_de_registros/registro/registro.sim/sim_1/behav/xsim/xsim.dir/tb_registro_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
