# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Ray/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-3468-DESKTOP-266QRLB/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.cache/wt [current_project]
set_property parent.project_path C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/new/Arc_Reg.vhd
  {C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Archivo_de_registros/Barrel/Barrel.srcs/sources_1/imports/Archivo de registros/Barrel.vhd}
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Unid_control/Bloq_Cond/Bloq_Cond.srcs/sources_1/new/Bloq_Cond.vhd
  {C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Unid_control/Bloque de Nivel/Bloque de Nivel.srcs/sources_1/new/Bloq_Nivel.vhd}
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Unid_control/Deco_Instru/Deco_Instru.srcs/sources_1/new/Deco_Instru.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/new/paquete.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Unid_control/MfunCode/MfunCode.srcs/sources_1/new/MfunCode.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Unid_control/MopCode/MopCode.srcs/sources_1/new/MopCode.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Unid_control/Mux20/Mux20.srcs/sources_1/new/Mux20.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Unid_control/Mux5/Mux5.srcs/sources_1/new/Mux5.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Unid_control/Registro/Registro.srcs/sources_1/new/Registro.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/ESCOMips/SDMP/SDMP.srcs/sources_1/new/SDMP.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/ESCOMips/SEXT/SEXT.srcs/sources_1/new/SEXT.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/ESCOMips/SR2/SR2.srcs/sources_1/new/SR2.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/ESCOMips/SWD/SWD.srcs/sources_1/new/SWD.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Unid_control/UC_F/UC_F.srcs/sources_1/new/UC_F.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Unid_control/Uni_Con/Uni_Con.srcs/sources_1/new/Uni_Con.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Arquitectura/alu1/alu1.srcs/sources_1/new/alu1.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/new/aluN.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Archivo_de_registros/demux16/demux16.srcs/sources_1/new/demux_16.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/ESCOMips/extDIR/extDIR.srcs/sources_1/new/extDIR.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/ESCOMips/extSIG/extSIG.srcs/sources_1/new/extSIG.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/new/mem_program.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/new/memo_dato.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Archivo_de_registros/mux2_a_1/mux2_a_1.srcs/sources_1/new/mux2_1.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Archivo_de_registros/multiplexor16/multiplexor16.srcs/sources_1/new/mux_16.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/new/pila.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Archivo_de_registros/registro/registro.srcs/sources_1/new/registro1.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/imports/Arquitectura/Sumadorestador/Sumadorestador.srcs/sources_1/new/suma1.vhd
  C:/Users/Ray/Desktop/Arquitectura/ESCOMips/ESCOMMips/ESCOMMips.srcs/sources_1/new/ESCOMMips.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ESCOMMips -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ESCOMMips.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ESCOMMips_utilization_synth.rpt -pb ESCOMMips_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
